name: frontend-ci

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          node-version: 20
      - run: npm ci
      - run: npm run -w frontend-react lint
      - run: npm run -w frontend-react build
